# See the following link for more info:
#   https://docs.spring.io/spring-boot/docs/1.4.x/reference/html/common-application-properties.html
server:
  port: 8000

logging:
  level:
    root: trace
    org.springframework.core.env.StandardEnvironment: error
    org.springframework: error
    org.apache: error
    com.netflix.config.sources: error
    org.hibernate: error
    com.existme.spike: trace
    org.springframework.util: error
    org.springframework.boot: error
  file: /tmp/spring.log
  pattern:
#     Original pattern 
#    console: '%clr{%d{yyyy-MM-dd HH:mm:ss.SSS}}{faint} %clr{%5p} %clr{${sys:PID}}{magenta} %clr{---}{faint} %clr{[%15.15t]}{faint} %clr{%-40.40c{1.}}{cyan} %clr{:}{faint} %m%n%xwEx %-40.40c{1.} : %m%n%ex'
#     See http://log4jtester.com/ for more info 
#    Shorter version with some ascii marker  uses NerdFonts symbols
    console: '%clr{%d{HH:mm:ss}}{faint} %clr{%5p} %clr{}{red} %clr{░░▒▒▓▓██ }{faint} %clr{%l}{cyan}{faint} %clr{:}{cyan} %clr{ ██▓▓▒▒░░}{faint}%n %m%n%ex%n'
spring:
  application:
    name: spike

feign:
  client:
    config:
#      pinboard:
#        root: https://api.pinboard.in/v1
      oidc:
        root: https://samples.auth0.com/
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
      oidcClient:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
#        errorDecoder: com.example.SimpleErrorDecoder
#        retryer: com.example.SimpleRetryer
#        requestInterceptors:
#          - com.example.FooRequestInterceptor
#          - com.example.BarRequestInterceptor
#        decode404: false
#        encoder: com.example.SimpleEncoder
#        decoder: com.example.SimpleDecoder
#        contract: com.example.SimpleContract

spike:
  message: "Hello from spike project"
flyway:
  url: